"""Render the version homepage and sitemaps for a complete documentation tree."""

from html import escape
from urllib.parse import quote
import xml.etree.ElementTree as ET


INDEX_HTML = """<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1" charset="UTF-8">
    <title>ConnectBot Terminal — Documentation</title>
    <link href="main/images/logo-icon.svg" rel="icon" type="image/svg">
    <script>document.documentElement.classList.replace("no-js", "js");</script>
    <script>
        const storage = localStorage.getItem("dokka-dark-mode");
        if (storage == null) {
            if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches)
                document.documentElement.classList.add("theme-dark");
        } else if (JSON.parse(storage) === true) {
            document.documentElement.classList.add("theme-dark");
        }
    </script>
    <link href="main/styles/style.css" rel="stylesheet">
    <link href="main/styles/main.css" rel="stylesheet">
    <link href="main/styles/logo-styles.css" rel="stylesheet">
    <link href="main/ui-kit/ui-kit.min.css" rel="stylesheet">
    <script src="main/ui-kit/ui-kit.min.js" defer></script>
    <style>
        .version-index { max-width: 860px; margin: 48px auto; padding: 0 24px; }
        .version-index h1 { margin-top: 0; }
    </style>
</head>
<body>
<div class="root">
    <header class="navigation theme-dark" id="navigation-wrapper" role="banner">
        <a class="library-name--link" href="${BASE_URL}/index.html" tabindex="1">ConnectBot Terminal</a>
        <div class="navigation-controls">
            <button class="navigation-controls--btn navigation-controls--btn_theme" id="theme-toggle-button" type="button">Switch theme</button>
        </div>
    </header>
    <div id="container">
        <div id="main" data-item-type="SECTION" role="main">
            <div class="main-content version-index" id="content">
                <h1 class="cover">ConnectBot Terminal</h1>
                <div class="platform-hinted UnderCoverText">
                    <div class="content">
                        <p class="paragraph">ConnectBot Terminal is a high-performance Jetpack Compose terminal emulator component for Android, providing accurate VT100/ANSI terminal emulation via libvterm.</p>
                    </div>
                </div>
                <h2>Documentation versions</h2>
                <div class="table">
${VERSION_ROWS}                </div>
            </div>
            <div class="footer">
                <div class="footer--container">
                    <a href="#content" id="go-to-top-link" class="footer--button footer--button_go-to-top"></a>
                    <div class="footer--content">
                        <div>
                            <span>Generated by </span>
                            <a class="footer--link footer--link_external" href="https://github.com/Kotlin/dokka">Dokka</a>
                            <div>Copyright Kenny Root</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    document.getElementById("theme-toggle-button").addEventListener("click", () => {
        const isDark = document.documentElement.classList.toggle("theme-dark");
        localStorage.setItem("dokka-dark-mode", isDark);
    });
</script>
</body>
</html>\n"""


def generate_site(output, versions, base_url):
    """Versions are supplied in display order: main, then descending releases."""
    available = [name for name in versions if (output / name / "index.html").is_file()]
    sitemap_index = ET.Element("sitemapindex", xmlns="http://www.sitemaps.org/schemas/sitemap/0.9")
    rows = []
    for name in available:
        sitemap = ET.Element("urlset", xmlns="http://www.sitemaps.org/schemas/sitemap/0.9")
        for page in sorted((output / name).rglob("*.html")):
            if page.name == "navigation.html":
                continue
            entry = ET.SubElement(sitemap, "url")
            ET.SubElement(entry, "loc").text = base_url + "/" + quote(page.relative_to(output).as_posix(), safe="/")
        ET.ElementTree(sitemap).write(output / name / "sitemap.xml", encoding="utf-8", xml_declaration=True)
        entry = ET.SubElement(sitemap_index, "sitemap")
        ET.SubElement(entry, "loc").text = f"{base_url}/{quote(name, safe='')}/sitemap.xml"
        label = 'main <span class="platform-tag jvm-like">snapshot</span>' if name == "main" else escape(name)
        href = escape(f"{base_url}/{quote(name, safe='')}/index.html", quote=True)
        rows.append('      <div class="table-row table-row_platform-tagged">'
                    '<div><div class="main-subrow"><div><span class="inline-flex">'
                    f'<a href="{href}">{label}</a></span></div></div></div></div>\n')
    if "main" not in available:
        return False
    index = INDEX_HTML.replace("${BASE_URL}", escape(base_url, quote=True)).replace("${VERSION_ROWS}", "".join(rows))
    (output / "index.html").write_text(index, encoding="utf-8")
    ET.ElementTree(sitemap_index).write(output / "sitemap_index.xml", encoding="utf-8", xml_declaration=True)
    return True
