#!/usr/bin/env python3
"""Generate terminal emoji tables from pinned Unicode data (no runtime downloads).

Run with --download to refresh the versioned cache, or --check to verify output.
"""
import argparse
import hashlib
import itertools
from pathlib import Path
import urllib.request

VERSION = "17.0.0"
ROOT = Path(__file__).resolve().parents[1]
CACHE = ROOT / "tools" / "unicode" / VERSION
FILES = {
    "emoji-data.txt": f"https://www.unicode.org/Public/{VERSION}/ucd/emoji/emoji-data.txt",
    "emoji-variation-sequences.txt": f"https://www.unicode.org/Public/{VERSION}/ucd/emoji/emoji-variation-sequences.txt",
    "emoji-sequences.txt": f"https://www.unicode.org/Public/{VERSION}/emoji/emoji-sequences.txt",
    "emoji-zwj-sequences.txt": f"https://www.unicode.org/Public/{VERSION}/emoji/emoji-zwj-sequences.txt",
}
OUTPUT = ROOT / "lib/src/main/cpp/libvterm/src/emoji.inc"


def records(name):
    for line in (CACHE / name).read_text().splitlines():
        line = line.split("#", 1)[0].strip()
        if line:
            yield [part.strip() for part in line.split(";")]


def ranges(values):
    for _, group in itertools.groupby(enumerate(sorted(values)), lambda pair: pair[1] - pair[0]):
        items = [value for _, value in group]
        yield items[0], items[-1]


def generate():
    lines = [f"/* Generated by tools/generate-unicode.py; Unicode {VERSION}. */"]
    for name in FILES:
        digest = hashlib.sha256((CACHE / name).read_bytes()).hexdigest()
        lines.append(f"/* {name}: sha256 {digest} */")
    properties = {}
    for code, prop, *_ in records("emoji-data.txt"):
        bounds = code.split("..")
        properties.setdefault(prop, set()).update(range(int(bounds[0], 16), int(bounds[-1], 16) + 1))
    for prop in ("Emoji_Presentation",):
        lines.append(f"static const struct interval {prop.lower()}[] = {{")
        lines.extend(f"  {{0x{start:X}, 0x{end:X}}}," for start, end in ranges(properties[prop]))
        lines.append("};")
    sequences = set()
    for name in ("emoji-sequences.txt", "emoji-zwj-sequences.txt", "emoji-variation-sequences.txt"):
        for codes, *_ in records(name):
            if ".." in codes:
                start, end = codes.split("..")
                sequences.update((cp,) for cp in range(int(start, 16), int(end, 16) + 1))
            else:
                sequences.add(tuple(int(cp, 16) for cp in codes.split()))
    assert max(map(len, sequences)) <= 16, "Increase native cell capacity for this Unicode release"
    # A sorted trie: sibling edges are linked; prefix recognition is bounded by
    # sequence length and never scans the thousands of complete sequences.
    trie = {}
    for sequence in sorted(sequences):
        node = trie
        for cp in sequence:
            node = node.setdefault(cp, {})
        node[None] = True
    nodes = [[0, 0, 0, 0]]

    def emit(branch):
        first = previous = 0
        for cp in sorted(key for key in branch if key is not None):
            index = len(nodes)
            nodes.append([cp, 0, 0, int(None in branch[cp])])
            if previous:
                nodes[previous][2] = index
            else:
                first = index
            previous = index
            nodes[index][1] = emit(branch[cp])
        return first

    emit(trie)
    lines.append("static const struct emoji_node { uint32_t cp; unsigned short child, next; unsigned char complete; } emoji_nodes[] = {")
    assert len(nodes) < 65536
    lines.extend(f"  {{0x{cp:X}, {child}, {next_node}, {complete}}}," for cp, child, next_node, complete in nodes)
    lines.append("};")
    roots = []
    index = 1
    while index:
        roots.append(index)
        index = nodes[index][2]
    lines.append("static const unsigned short emoji_roots[] = {" + ", ".join(map(str, roots)) + "};")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--download", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.download:
        CACHE.mkdir(parents=True, exist_ok=True)
        for name, url in FILES.items():
            with urllib.request.urlopen(url, timeout=30) as response:
                (CACHE / name).write_bytes(response.read())
    result = generate()
    if args.check:
        assert OUTPUT.read_text() == result, "Unicode tables need regeneration"
    else:
        OUTPUT.write_text(result)
