name: Release
on:
  issues:
    types: [labeled]

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: read
  checks: read
  statuses: read

jobs:
  prepare:
    if: github.event.label.name == 'release:prepare'
    uses: connectbot/actions/.github/workflows/prepare-release.yml@main
    with:
      tag_prefix: ""
      gradle_no_push_prop: "release.noPush"
    secrets: inherit

  publish:
    if: github.event.label.name == 'release:publish'
    uses: connectbot/actions/.github/workflows/publish-release.yml@main
    with:
      tag_prefix: ""
    secrets: inherit

  branch:
    if: github.event.label.name == 'release:branch'
    uses: connectbot/actions/.github/workflows/release-branch.yml@main
    secrets: inherit
